[package]
name = "logtra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
contra = "5.0.1"
lib-contra = "5.0.1"
proc-contra = "5.0.1"
