name: Version

on:
  push:
    branches:
     - "master"

jobs:
  version:
    if: "!startsWith(github.event.head_commit.message, '[PUBLISH]: ')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-workspaces
          version: latest

      - name: "Default version bump: patch" 
        run: echo "BUMP=patch" >> $GITHUB_ENV
      - name: "Determine version bump: minor" 
        run: echo "BUMP=minor" >> $GITHUB_ENV
        if: contains(github.event.head_commit.message, 'feat/')
      - name: "Determine version bump: major" 
        run: echo "BUMP=major" >> $GITHUB_ENV
        if: contains(github.event.head_commit.message, 'release/')

      - name: "Setup Git Credentials"
        run: |
            git config --global user.name "Github Action Bot: Version"
            git config --global user.email "<>"
      - name: Upgrade Version
        run: "cargo ws version $BUMP -a --exact --force '*' -y --no-individual-tags -m '[PUBLISH]: %v'"
